### ISSUE TITLE
Windows shared library build fails with LNK1104: cannot open file '..\glslang\Debug\glslang-default-resource-limitsd.lib'

### ISSUE THREAD

**Issue by AnyOldName3** [KhronosGroup/glslang#3716]
I just tried a DLL build of glslang (passed `-DBUILD_SHARED_LIBS` to CMake), and hit three fatal errors. Two were `fatal error LNK1104: cannot open file '..\glslang\Debug\glslang-default-resource-limitsd.lib'` and one was `fatal error LNK1104: cannot open file '..\SPIRV\Debug\SPVRemapperd.lib'`. The files are specified with the `/IMPLIB` flag for the linker commands that would be expected to generate them.

I've had a look at the DLLs with this tool https://github.com/lucasg/Dependencies and it seems that they don't actually export any symbols. MSVC doesn't bother to emit an import library when a DLL exports no symbols. You can make GCC behave like MSVC here (and shrink binary size) by passing `-fvisibility=hidden` and marking everything as `__attribute__((__visibility__("default")))` if it'd be `__declspec(dllexport)` with MSVC.

It's possible that some `GLSLANG_EXPORT` macro calls are missing and symbols are supposed to be exported but aren't - after all, GCC and Clang both export all symbols by default, so it's easy to miss. If no functions are exported, linking with these DLLs won't do anything other than running their static initialisers and destructors, and none of their functions will be callable. Looking at the headers for these libraries, it certainly *looks* like there are functions that should be callable.

When this is fixed, I'd suggest adding a Windows DLL build to the CI so it doesn't get broken again.

**Comment by arcady-lunarg** [comment]
Now that we've factored out `visibility.h` into its own header, this should be pretty straightforward to add. This also needs to be done for the SPV remapper, especially because there are global symbols that clash between SPVRemapper and glslang libraries and they get linked together into the `glslangtests` binary.

**Comment by arcady-lunarg** [comment]
@AnyOldName3 could you give it a try with #3725? That should fix the issues with those libraries in particular, though I'm not entirely sure that glslang.dll will be exporting the correct set of symbols but we're working on getting everything exported correctly so that we can have a fully functional shared library build not just on unix but on windows as well.

**Comment by arcady-lunarg** [comment]
Thanks, I will have fixes for the other stuff shortly, just need to do a
bit more testing before I push it.

**Comment by arcady-lunarg** [comment]
FYI, #3726 is the next one, removing the direct dependency on the `TDefaultGlslIoResolver` and `TGlslIoMapper` classes. The other ones are going to be fixed soon as well. One thing I am curious about @AnyOldName3 if whether putting the `GLSLANG_EXPORT` macro on, say, a method definition (in the .cpp file) rather than the declaration (in the .h file) would work on Windows.

**Comment by AnyOldName3** [comment]
I just tried it and the compiler emits `error C2375: 'functionNameHere': redefinition; different linkage` if the declaration isn't `__declspec(dllexport)` but the definition is.

**Comment by AnyOldName3** [comment]
With the current commit of main, I still can't build the project in shared library mode due to:
```
27>StandAlone.obj : error LNK2019: unresolved external symbol "void __cdecl glslang::OS_DumpMemoryCounters(void)" (?OS_DumpMemoryCounters@glslang@@YAXXZ) referenced in function "void __cdecl CompileFile(char const *,void *)" (?CompileFile@@YAXPEBDPEAX@Z)
```
stopping the standalone compiler from building and
```
26>VkRelaxed.FromFile.obj : error LNK2019: unresolved external symbol "public: bool __cdecl glslang::TReflection::addStage(enum EShLanguage,class glslang::TIntermediate const &)" (?addStage@TReflection@glslang@@QEAA_NW4EShLanguage@@AEBVTIntermediate@2@@Z) referenced in function "bool __cdecl glslangtest::`anonymous namespace'::verifyIOMapping(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class glslang::TProgram &)" (?verifyIOMapping@?A0xb0da8d00@glslangtest@@YA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVTProgram@glslang@@@Z)
26>GlslMapIO.FromFile.obj : error LNK2019: unresolved external symbol "public: static int __cdecl glslang::TIntermediate::computeTypeLocationSize(class glslang::TType const &,enum EShLanguage)" (?computeTypeLocationSize@TIntermediate@glslang@@SAHAEBVTType@2@W4EShLanguage@@@Z) referenced in function "bool __cdecl glslangtest::`anonymous namespace'::verifyIOMapping(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class glslang::TProgram &)" (?verifyIOMapping@?A0x60400b42@glslangtest@@YA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVTProgram@glslang@@@Z)
```
stopping the tests from building.

Like before, exporting those functions in their headers removed those errors, but unlike before, now #3726 is merged, the other errors are gone, too, so it actually builds. This is available as https://github.com/AnyOldName3/glslang/tree/more-exports. I can open a PR if they're supposed to be exported, but if, like the IO mapper, they're not supposed to be part of the public API, that won't be a solution.

**Comment by AnyOldName3** [comment]
If I build the install target locally, I can see that those headers aren't installed, so either they need to be, or these symbols need dealing with some other way.
