### ISSUE TITLE
HLSL: max is ambigous for scaler cases where it clearly shouldn't be ambigous

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/glslang#609]
Simple shader
```
float4 main(float globalAlphaMask : TexCoord1) : SV_TARGET
{
   float Alpha = max(0, globalAlphaMask);
   return Alpha.xxxx;
}
```

which compiles fine with fxc, but I get the message:
```
ERROR: HLSLTest.hlsl:3: 'max' : ambiguous best function under implicit type conversion
HLSLTest.hlsl(3): error at column 53, HLSL parsing failed.
```

I can fix the issue by explicitly making the '0' a float:
```
float4 main(float globalAlphaMask : TexCoord1) : SV_TARGET
{
   float Alpha = max(float(0), globalAlphaMask);
   return Alpha.xxxx;
}
```
So looks to me like might be some general case where there are 2 promotions possible for scalars and it's getting confused, however it's pretty weird for a max of 0 with a float to not be able to return a float without a cast.

**Comment by zeux** [comment]
I believe this is addressed by #577, at least on our codebase. Hopefully it gets merged soon.

**Comment by johnkslang** [comment]
Yes, looks okay now.

**Comment by steve-lunarg** [comment]
Note also that #577 solves about 95% of the problem, but in some cases an opcode specific distinction is required but is currently lost.  I have another WIP I'll try to finish up shortly for that dimension of the problem.  Before it, there are some cases which can still fail, but they should be addressed soon.
