### ISSUE TITLE
HLSL: Explicit descriptor offsets for b#, t#, s#, u#

### ISSUE THREAD

**Issue by punkUser** [KhronosGroup/glslang#794]
As with many other folks, when compiling HLSL shaders we need a way to map the four standard HLSL binding namespaces (cbuffers: b#, SRVs: t#, samplers: s# and UAVs: u#) to unique descriptor indices in SPIRV/Vulkan. Since our shaders have a mix of explicit and implicit mappings, the best way to guarantee they end up unique is to just assign ranges in the resulting descriptor set for each of the binding spaces.

There's some support for this with the IoRemapper for this in the "set shift [] binding", but the naming of these implies it's more in terms of the Vulkan types rather than the HLSL namespaces. While in a lot of cases there's a 1:1 mapping between these, there are certainly cases today where this is not the case and it's probably not something we want to always assume will be perfect 1:1 in the future.

Thus what we'd really like to see in the HLSL path is:

1) Auto map bindings done in the HLSL namespaces before translation, similar to what FXC would do. Doesn't have to match perfectly, but should be done in those namespaces to ensure uniqueness.

2) Application provides 4 offsets - one each for b#, t#, s# and u# - named as per the HLSL conversions. ex. Cbuffer offset, SRV offset, UAV offset, sampler offset. When mapping the now fully resolved bindings from HLSL one simply adds the namespace offset to the #.

Today we're implementing something similar by modifying the IoRemapper but it would be great to have this directly done as described above for future compatibility and to ensure that the semantics we're looking for remain.

Thanks!

**Comment by danginsburg** [comment]
To add some more detail, because I had a conversation with @punkUser and at first didn't understand the ask here.  So related to #795 I believe what he is saying is that in HLSL both Buffer<> and regular textures share a namespace t#.  That is, both textures and texture buffers are specified in HLSL with t#.  In the I/O remapper, these are treated as different binding spaces (Buffer<> currently as Ssbo although that's possibly wrong, depends on how #795 is resolved) and textures as textures.  

He wants to be able to preserve the t# even though in Vulkan these are going to correspond to different resource types.  So whereas now the I/O remapper would treat the Buffer<> and textures as separate namespaces with different starting offsets, he wants to use the same namespace.

I think maybe if the I/O remapper was able to specify shift bindings in an alternate way using HLSL namespaces that might give him what he wants.

**Comment by johnkslang** [comment]
> He wants to be able to preserve the t# even though in Vulkan these are going to correspond to different resource types.

If we follow the current direction of #795, they will map to the same type, and maybe this cancels out? But, is the same question just re-raised with `StructuredBuffer<>`, because we still don't plan to map them to SPIR-V images?

**Comment by punkUser** [comment]
Yeah, that's correct - the way we map HLSL "types" to SPIR-V is not entirely 1:1 and thus the only way to be sure things remain unique is really to do the offsets/assignments in the spaces that we know they were unique to begin with - i.e. the 4 HLSL namespaces.

**Comment by danginsburg** [comment]
Upon further review of #795 I have realized that we have the same requirement here as @punkUser.  When I grabbed glslang master containing PR #811 and tried to implement support for Buffer<> in our engine I ran into the same namespace issue.

Currently (post PR #811), glslang will treat Buffer<> as a uniform texel buffer and apply the offset in the I/O remapper given for TShader::setShiftTextureBinding which will make Buffer<> use the same binding space as textures.  That part is fine, but then if the shader also has StructuredBuffer<> it applies the TShader::setShiftSsboBinding for the SSBO binding.  Where I get into trouble is that Buffer<> and StructuredBuffer<> and Texture were all expected to land in the t# namespace as far as the engine code is concerned (which follows HLSL conventions).  

My suggestion is the same as @punkUser, that is the remapper should be modified to have the following interfaces:

  // These two already exist:
  setShiftSamplerBinding(unsigned int base);
  setShiftTextureBinding(unsigned int base);
  // And then:
  setShiftUAVBinding(unsigned int base);
  setShiftCbufferBinding(unsigned int base);
  // And remove:
  setShiftImageBinding()
  setShiftUboBinding() (note this is the same as setShiftCbufferBinding above - just suggesting cbuffer to match HLSL naming)
  setShiftBindingSsboBinding()

HLSL has four namespaces (https://msdn.microsoft.com/en-us/library/windows/desktop/dn899207(v=vs.85).aspx) and each of these in the I/O remapper correspond to one of them:

t – for shader resource views (SRV)
s – for samplers
u – for unordered access views (UAV)
b – for constant buffer views (CBV)

You can figure out which resource maps to which type by testing with fxc, for example for Buffer<>, StructuredBuffer<> RWTexture you would see this:

	StructuredBuffer<BufType> Buffer0 ;
	StructuredBuffer<BufType> Buffer1 ;
	Buffer<float4> Buffer2 ;
	RWTexture2D<float4> OutputTexture ;


// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// Buffer0                           texture  struct         r/o    0        1
// Buffer1                           texture  struct         r/o    1        1
// Buffer2                           texture  float4         buf    2        1
// OutputTexture                         UAV  float4          2d    0        1

If we want to keep both the existing behavior and the one suggested on this bug, perhaps there could be two variants of the I/O remapper (or some interface that allows either to be chosen), one which uses the suggested namespaces on this bug and another which makes each unique.  If we are to make each unique, one thing that is quite inconsistent in my view is that at the moment all Vulkan resource types map to their own range except Buffer<> which collapses on to texture because there is no setShiftBindingUniformTexelBufferBinding.

**Comment by steve-lunarg** [comment]
I can look into something like this after I get to a stopping point in something else I have going.  Agreed with your sentiment: we'll need to take some care with it, because there are consumers of the existing API.  Also, in theory I don't think there's anything to stop the current iomapper from being used with GLSL as well as HLSL, although maybe there's no one actually doing that.

**Comment by danginsburg** [comment]
I agree there might be existing users of the current API.  I am inclined to suggest we go two routes on this:

1. Add the new method of I/O remapping suggested in this bug without disturbing the existing interface.
2. Modify the existing interface to have setShiftUniformTexelBufferBinding because I personally don't think the existing interface makes sense for that particular resource (it is the only outlier where the Vulkan resource type doesn't map to its own range)

**Comment by steve-lunarg** [comment]
There are a few small corners left, but there's some work on this in #840.  You can say --hlsl-iomap on the command line to perform the mapping in HLSL register space.  If you don't say that, existing behavior is unperturbed.  (I.e, it does not yet implement @danginsburg's suggestion about  setShiftUniformTexelBufferBinding).

There are some new API and command line switches: --shift-cbuffer-binding is a synonym, and --shift-uav-binding is new.

I know of one problem: tbuffers end up in the wrong register class.  I don't know why, but will investigate that.

A new HLSL io resolver class is defined in iomapper.cpp.  It would probably be better to pass it in as an IO mapper to mapIO() instead, though that will take more code reshuffling, so maybe is best left to its own change.

This is in a separate PR from the still-WIP #835 which adds counter buffer methods, but I expect this to "just work" with AppendStructuredBuffer/ConsumeStructuredBuffer types when #835 is in place.

Except for the aforementioned trouble with tbuffer, these should be the mappings with the --hlsl-iomap option enabled:

```
t – for shader resource views (SRV)
//      | TEXTURE1D
//      | TEXTURE1DARRAY
//      | TEXTURE2D
//      | TEXTURE2DARRAY
//      | TEXTURE3D
//      | TEXTURECUBE
//      | TEXTURECUBEARRAY
//      | TEXTURE2DMS
//      | TEXTURE2DMSARRAY
//      | STRUCTUREDBUFFER
//      | BYTEADDRESSBUFFER
//      | BUFFER
//      | TBUFFER
    
s – for samplers
//      | SAMPLER
//      | SAMPLER1D
//      | SAMPLER2D
//      | SAMPLER3D
//      | SAMPLERCUBE
//      | SAMPLERSTATE
//      | SAMPLERCOMPARISONSTATE

u – for unordered access views (UAV)
//      | RWBYTEADDRESSBUFFER
//      | RWSTRUCTUREDBUFFER
//      | APPENDSTRUCTUREDBUFFER
//      | CONSUMESTRUCTUREDBUFFER
//      | RWBUFFER
//      | RWTEXTURE1D
//      | RWTEXTURE1DARRAY
//      | RWTEXTURE2D
//      | RWTEXTURE2DARRAY
//      | RWTEXTURE3D

b – for constant buffer views (CBV) (UBO)
//      | CBUFFER

```

**Comment by danginsburg** [comment]
I have tested #840 here and can confirm that it is working as I would expect and I can now mix Buffer, StructuredBuffer, and RWTexture in a shader and they end up in the correct t# vs u# space.

**Comment by steve-lunarg** [comment]
OK, I've fixed the aforementioned trouble with tbuffer: they're marked as readonly now, which gets them into the SRV (t#) register space.  If that doesn't sound right, please speak up :).

Also improved the comments a bit: the TDefaultHlslIoResolver class explicitly gives the mappings that it applies.
